// <auto-generated />
namespace Doan16.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BK_HoaDon_CTHoaDon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BK_HoaDon_CTHoaDon));
        
        string IMigrationMetadata.Id
        {
            get { return "201805290318293_BK_HoaDon_CTHoaDon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
