// <auto-generated />
namespace Doan16.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeNull_PhanQuyen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeNull_PhanQuyen));
        
        string IMigrationMetadata.Id
        {
            get { return "201805231613508_removeNull_PhanQuyen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
